version: '3'

services:
  database:
    image: 'bitnami/postgresql:latest'
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

networks: 
  postgres-network:
    driver: bridge