# --- Active profiles ---
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# --- DB timeout --
javax:
  persistence:
    query:
      timeout: 10000