# --- Data source ---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console